export const NAMESPACE = 'auth'

//actions
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SETUSERLOGGED = 'SET_USER_LOGGED'

export const SETCOGNITOTOKEN = 'SET_COGNITO_TOKEN'
export const GETAUTHENTICATEDUSER = 'GET_AUTHENTICATED_USER'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_OK = 'RESET_PASSWORD_OK'
